name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Build and package
      run: |
        cd linux
        pip3 install --upgrade pip
        ./build.sh
    
    - name: Run
      run: |
        cd linux
        ./Remote-PC
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-linux
        path: ./linux/Remote-PC
    
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Build and package
      run: |
        cd ./windows
        pip install --upgrade pip
        ./build.bat
    - name: Run
      run: |
        cd ./windows
        ./Remote-PC.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-windows
        path: ./windows/Remote-PC.exe